version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/lara
    depends_on:
      - mysql
      - php
    container_name: nginx
  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/lara
    container_name: php
  mysql:
    image: mysql:8.0
    ports:
      - "3326:3306"
    env_file:
      - env/mysql.env
    environment:
      MYSQL_DATABASE: catalog-3
      MYSQL_USER: catalog-3
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./tmp/db_data:/var/lib/mysql
    container_name: mysql

  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/lara
    container_name: composer
  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/lara
    entrypoint: ["php", "/var/www/lara/artisan"]
    container_name: artisan

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    depends_on:
      - mysql
    environment:
      PMA_USER: default-db
      PMA_PASSWORD: "B&hd9QrveFX&"
      PMA_HOSTS: mysql,localhost
      UPLOAD_LIMIT: 120M
    container_name: phpmyadmin



